#ifndef NLP_ENGINE_ASYNC_HH
#define NLP_ENGINE_ASYNC_HH

#include <string>
#include <memory>
#include <functional>
#include <future>
#include <queue>
#include <mutex>
#include <condition_variable>
#include <thread>
#include <unordered_map>
#include <vector>

#include "nlp_engine.hh"
#include "nlp_addon_system.hh"

/**
 * @namespace pce::nlp
 * @brief Root namespace for the PCE NLP Engine components.
 */
namespace pce::nlp {

// ============ Stream callbacks ============

/**
 * @brief Callback for streaming text chunks.
 * @param chunk The text chunk generated by the engine.
 * @param is_final Boolean indicating if this is the last chunk of the stream.
 */
using StreamCallback = std::function<void(const std::string& chunk, bool is_final)>;

/**
 * @brief Callback for completion of non-streaming async tasks.
 * @param result The final result string.
 * @param success Boolean indicating if the operation completed successfully.
 */
using CompletionCallback = std::function<void(const std::string& result, bool success)>;

// ============ Data Structures ============

/**
 * @struct AsyncResult
 * @brief Represents the result of an asynchronous NLP task.
 */
struct AsyncResult {
    std::string result;     ///< The processed text or serialized JSON result.
    bool success;           ///< Whether the task completed without errors.
    std::string error;      ///< Error message if success is false.
    std::string task_id;    ///< Unique identifier for the task.
};

/**
 * @class AsyncTaskManager
 * @brief Manages the lifecycle and execution of asynchronous tasks.
 */
class AsyncTaskManager {
private:
    std::unordered_map<std::string, std::future<AsyncResult>> tasks_;
    std::vector<std::thread> workers_;
    std::mutex tasks_mutex_;

public:
    ~AsyncTaskManager() {
        for (auto& t : workers_) {
            if (t.joinable()) t.join();
        }
    }

    std::string submit_task(std::function<AsyncResult()> task);
    AsyncResult get_result(const std::string& task_id, bool wait = true);
    void cancel_task(const std::string& task_id);
    bool is_task_complete(const std::string& task_id);
};

/**
 * @class AsyncNLPEngine
 * @brief High-performance asynchronous wrapper for the NLP Engine and its Addons.
 */
class AsyncNLPEngine {
private:
    std::shared_ptr<NLPModel> model_;
    std::unique_ptr<AsyncTaskManager> task_manager_;

    // Addon storage: Using polymorphic pointers to ensure visibility across language boundaries.
    std::unordered_map<std::string, std::shared_ptr<INLPAddon>> addons_;
    std::mutex addons_mutex_;

    // Context storage: Persistent state for sessions or documents.
    std::unordered_map<std::string, std::shared_ptr<AddonContext>> contexts_;
    std::mutex contexts_mutex_;

    bool is_running_;

public:
    explicit AsyncNLPEngine(std::shared_ptr<NLPModel> model);
    ~AsyncNLPEngine();

    bool initialize();
    bool shutdown();

    // --- Addon Management ---

    /**
     * @brief Adds a new Addon to the engine.
     * @param addon A shared pointer to an object implementing INLPAddon.
     * @return True if the addon was registered.
     */
    bool add_addon(std::shared_ptr<INLPAddon> addon);

    /**
     * @brief Removes an addon by name.
     * @param name The unique name of the addon.
     * @return True if found and removed.
     */
    bool remove_addon(const std::string& name);

    /**
     * @brief Checks if a specific addon is available.
     * @param name Name of the addon.
     */
    bool has_addon(const std::string& name);

    /**
     * @brief Gets all registered addons.
     * @return A map of addon names to their shared pointers.
     */
    std::unordered_map<std::string, std::shared_ptr<INLPAddon>> get_all_addons() {
        std::lock_guard<std::mutex> lock(addons_mutex_);
        return addons_;
    }

    // --- Processing API ---

    std::string process_sync(
        const std::string& text,
        const std::string& method,
        const std::unordered_map<std::string, std::string>& options = {},
        const std::string& session_id = ""
    );

    std::string process_text_async(
        const std::string& text,
        const std::string& addon_name,
        StreamCallback stream_callback = nullptr,
        const std::unordered_map<std::string, std::string>& options = {},
        const std::string& session_id = ""
    );

    std::string submit_task(
        std::function<AsyncResult()> task,
        const std::string& task_name = ""
    );

    AsyncResult get_task_result(const std::string& task_id);

    void stream_text(
        const std::string& text,
        const std::string& addon_name,
        StreamCallback callback,
        const std::unordered_map<std::string, std::string>& options = {},
        const std::string& session_id = ""
    );

    // --- Context Management ---

    /**
     * @brief Gets or creates a context for a specific session.
     */
    std::shared_ptr<AddonContext> get_context(const std::string& session_id);

    /**
     * @brief Clears a session context.
     */
    void clear_context(const std::string& session_id);
};

} // namespace pce::nlp

#endif // NLP_ENGINE_ASYNC_HH
