import os
import sys
import json
import logging
import asyncio
import psutil
import time
from typing import Dict, Any, Optional
from pathlib import Path
from dotenv import load_dotenv

# --- Environment Configuration ---
# Load .env file (generated by dev.sh)
# The .env file contains the path to the built C++ module
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

# Manually update sys.path if PYTHONPATH is in the environment
# python-dotenv loads it into os.environ, but it doesn't automatically update sys.path for the current process
if "PYTHONPATH" in os.environ:
    paths = os.environ["PYTHONPATH"].split(os.pathsep)
    for p in reversed(paths):
        if p and p not in sys.path:
            sys.path.insert(0, p)

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

# --- Native NLP Engine Integration ---
# We require the native nlp_engine module to be present.
try:
    from nlp_engine import AsyncNLPEngine
except ImportError as e:
    print(f"DEBUG: sys.path is {sys.path}")
    print(f"DEBUG: PYTHONPATH is {os.environ.get('PYTHONPATH')}")
    raise ImportError(
        f"Could not find the 'nlp_engine' native module. Error: {e}\n"
        "Please build it using './dev.sh --python' before starting the server."
    ) from e

app = FastAPI(title="NLP Engine API", version="2.0.0")
logger = logging.getLogger(__name__)

# Enable CORS for the React client
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# Initialize the native engine
engine = AsyncNLPEngine()

# Track active tasks for the profiler
active_tasks_tracker = {}

# --- Models ---

class ProcessingRequest(BaseModel):
    text: str
    plugin: str = "default"
    options: Dict[str, Any] = {}
    streaming: bool = False
    session_id: Optional[str] = None

class ProcessingResponse(BaseModel):
    result: str
    task_id: Optional[str] = None
    status: str = "completed"

# --- Lifecycle ---

@app.on_event("startup")
async def startup_event():
    """Initialize the native NLP engine and load resource dictionaries"""
    try:
        # Resolve path to the data directory containing dictionaries
        data_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../data"))

        if not engine.load_model(data_path):
            logger.error(f"Failed to load model resources from: {data_path}")

        engine.initialize()
        logger.info(f"Native NLP Engine initialized with resources from {data_path}")

        # Load available Markov models
        models_dir = os.path.join(data_path, "models")
        app.state.available_models = []
        if os.path.exists(models_dir):
            for model_file in os.listdir(models_dir):
                if model_file.endswith(".json"):
                    model_path = os.path.join(models_dir, model_file)
                    # We can load multiple but for now we register the generic one
                    # Register the model with its own name as the addon method
                    model_name = os.path.splitext(model_file)[0]
                    engine.load_markov_model(model_path, model_name)
                    logger.info(f"Registered Markov model: {model_name} from {model_file}")

                    # Store model name without extension
                    model_name = os.path.splitext(model_file)[0]
                    app.state.available_models.append(model_name)
    except Exception as e:
        logger.error(f"Failed to initialize native engine: {e}")
        # We don't necessarily want to kill the whole server if initialization fails during dev,
        # but for a production-ready app, we might.
        # raise RuntimeError(f"Engine initialization failed: {e}")

@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup native resources"""
    if engine:
        engine.shutdown()
        logger.info("Native NLP Engine shut down")

# --- Endpoints ---

@app.post("/detect-language")
async def detect_language(request: ProcessingRequest):
    """Granular: Detect language of the provided text"""
    try:
        res = engine.process_text_sync(request.text, "language", request.options)
        return json.loads(res)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/spell-check")
async def spell_check(request: ProcessingRequest):
    """Granular: Perform spell checking on the provided text"""
    try:
        # Default to 'en' if no language provided in options
        lang = request.options.get("lang", "en")
        res = engine.process_text_sync(request.text, "spell_check", request.options)
        return json.loads(res)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/sentiment")
async def analyze_sentiment(request: ProcessingRequest):
    """Granular: Analyze sentiment of the provided text"""
    try:
        res = engine.process_sync(request.text, "sentiment", request.options, request.session_id or "")
        return json.loads(res)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/generate")
async def generate_text(request: ProcessingRequest):
    """Generate text using a registered Markov model"""
    task_id = f"gen_{int(time.time() * 1000)}"
    active_tasks_tracker[task_id] = {"type": "MarkovGen", "start": time.time()}
    try:
        # Default to markov_generator if no specific addon provided
        method = request.plugin if request.plugin != "default" else "markov_generator"

        # Ensure all option values are strings for the C++ pybind interface
        safe_options = {k: str(v) for k, v in request.options.items()}
        res = engine.process_sync(request.text, method, safe_options, request.session_id or "")

        # Addons might return raw text or JSON depending on implementation
        try:
            return json.loads(res)
        except json.JSONDecodeError:
            return {"output": res, "status": "success"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        active_tasks_tracker.pop(task_id, None)

@app.get("/generate-stream")
async def generate_text_stream(
    seed: str,
    model: str = "generic_novel",
    length: int = 150,
    top_p: float = 0.9,
    semantic_filter: float = 0.0,
    session_id: Optional[str] = None
):
    """
    Stream Markov generation word-by-word.
    """
    task_id = f"gen_stream_{int(time.time() * 1000)}"
    active_tasks_tracker[task_id] = {"type": "MarkovStream", "start": time.time()}

    options = {
        "length": str(length),
        "top_p": str(top_p),
        "semantic_filter": str(semantic_filter)
    }

    queue = asyncio.Queue()
    loop = asyncio.get_event_loop()

    def cpp_callback(chunk: str, is_final: bool):
        loop.call_soon_threadsafe(queue.put_nowait, {"chunk": chunk, "is_final": is_final})

    async def event_generator():
        try:
            # Start the native streaming generation
            engine.stream_text(seed, model, cpp_callback, options, session_id or "")

            while True:
                data = await queue.get()
                yield f"data: {json.dumps(data)}\n\n"
                if data.get("is_final"):
                    break
        except Exception as e:
            logger.error(f"Error in Markov stream: {e}")
            yield f"data: {json.dumps({'chunk': '', 'is_final': True, 'error': str(e)})}\n\n"
        finally:
            active_tasks_tracker.pop(task_id, None)

    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.post("/semantic")
async def semantic_analysis(request: ProcessingRequest):
    """Semantic: Perform vector-based operations (similarity, clustering, outliers)"""
    task_id = f"vec_{int(time.time() * 1000)}"
    active_tasks_tracker[task_id] = {"type": "VectorEngine", "start": time.time()}
    try:
        # Default to vector_engine if no specific addon provided
        method = request.plugin if request.plugin != "default" else "vector_engine"

        # Ensure all option values are strings for the C++ pybind interface
        safe_options = {k: str(v) for k, v in request.options.items()}
        res = engine.process_sync(request.text, method, safe_options, request.session_id or "")

        try:
            return json.loads(res)
        except json.JSONDecodeError:
            return {"output": res, "status": "success"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        active_tasks_tracker.pop(task_id, None)

@app.post("/async-process")
async def async_process_text(request: ProcessingRequest):
    """Submit text to the C++ engine for asynchronous processing"""
    try:
        # Returns a unique task ID from the C++ AsyncTaskManager
        task_id = engine.process_text_async(request.text, request.plugin, request.options, request.session_id or "")
        return {"task_id": task_id, "status": "processing"}
    except Exception as e:
        logger.error(f"Async processing error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/stream/{task_id}")
async def stream_results(
    task_id: str,
    text: str,
    pos_tagging: Optional[str] = None,
    terminology: Optional[str] = None,
    safety: Optional[str] = None,
    session_id: Optional[str] = None
):
    """
    Bridge C++ callbacks into an SSE stream.
    The C++ engine calls the callback on its own thread; we use an asyncio.Queue
    to safely pass those chunks back to the FastAPI response stream.
    """
    if not text:
        raise HTTPException(status_code=400, detail="Text parameter is required for streaming")

    # Map query parameters to engine options
    options = {}
    if pos_tagging: options["pos_tagging"] = pos_tagging
    if terminology: options["terminology"] = terminology
    if safety: options["safety"] = safety

    queue = asyncio.Queue()
    loop = asyncio.get_event_loop()

    def cpp_callback(chunk: str, is_final: bool):
        # Thread-safe transfer from C++ worker thread to Python event loop
        loop.call_soon_threadsafe(queue.put_nowait, {"chunk": chunk, "is_final": is_final})

    async def event_generator():
        task_id = f"stream_{int(time.time() * 1000)}"
        active_tasks_tracker[task_id] = {"type": "LinguisticStream", "start": time.time()}
        try:
            # Start the native streaming process
            # The engine will trigger 'cpp_callback' multiple times
            engine.stream_text(text, "default", cpp_callback, options, session_id or "")

            while True:
                data = await queue.get()
                logger.debug(f"Streaming chunk: {data}")
                # Ensure the frontend receives the expected JSON structure
                # with the data: prefix for Server-Sent Events
                yield f"data: {json.dumps(data)}\n\n"
                if data.get("is_final"):
                    logger.info("Stream complete.")
                    break
        except Exception as e:
            logger.error(f"Error in SSE event generator: {e}")
            yield f"data: {json.dumps({'chunk': '', 'is_final': True, 'error': str(e)})}\n\n"
        finally:
            active_tasks_tracker.pop(task_id, None)

    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/health")
async def health_check():
    """Check engine readiness and resource status"""
    process = psutil.Process(os.getpid())

    # Get memory info (in MB)
    mem_info = process.memory_info()
    ram_usage_mb = mem_info.rss / (1024 * 1024)

    # Get CPU usage (this is a percentage)
    cpu_usage = process.cpu_percent(interval=None)

    # Calculate active task list
    now = time.time()
    active_tasks = [
        {"id": tid, "type": tdata["type"], "elapsed": round(now - tdata["start"], 1)}
        for tid, tdata in active_tasks_tracker.items()
    ]

    return {
        "status": "healthy",
        "engine_type": "native",
        "engine_ready": engine.is_ready() if engine else False,
        "available_models": getattr(app.state, "available_models", []),
        "stats" : {
            "ram_mb": round(ram_usage_mb, 2),
            "cpu_percent": cpu_usage,
            "uptime_seconds": int(now - process.create_time()),
            "threads": process.num_threads(),
            "active_tasks": active_tasks
        }
    }

# --- Static File Serving ---

CLIENT_PATH = os.path.join(os.path.dirname(__file__), "..", "client", "dist")

if os.path.exists(CLIENT_PATH):
    # Mount dist directory for direct asset access
    app.mount("/static", StaticFiles(directory=CLIENT_PATH), name="static")

    @app.get("/{full_path:path}")
    async def serve_react_app(full_path: str):
        # 1. Root path -> index.html
        if not full_path:
            return FileResponse(os.path.join(CLIENT_PATH, "index.html"))

        # 2. Direct file hit (JS, CSS, images)
        file_path = os.path.join(CLIENT_PATH, full_path)
        if os.path.isfile(file_path):
            return FileResponse(file_path)

        # 3. SPA Fallback for React Router
        return FileResponse(os.path.join(CLIENT_PATH, "index.html"))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
